apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-claim
  labels:
    type: local
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: tanzu-poc-rz2
  resources:
    requests:
      storage: 2Gi
  
  hostPath:
    path: /k8/volume/pv-1
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: wp-pv-claim
  labels:
    type: local
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: tanzu-poc-rz2
  resources:
    requests:
      storage: 2Gi
  hostPath:
    path: /k8/volume/pv-2